import 'package:flutter/material.dart';

class MyPrivacyState extends StatelessWidget {
  const MyPrivacyState({super.key});

  @override
    Widget build(BuildContext context) {
    return MaterialApp(
      home: PrivacyPolicyPage(),
    );
  }
}

class PrivacyPolicyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Privacy Policy'),
        backgroundColor: Colors.orange,
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Privacy Policy',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10),
            Text(
              'Last updated: August 26, 2024',
              style: TextStyle(fontSize: 16, fontStyle: FontStyle.italic),
            ),
            SizedBox(height: 20),
            Text(
              'This Privacy Policy describes Our policies and procedures on the collection, use, '
              'and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.',
              style: TextStyle(fontSize: 16),
            ),
            SizedBox(height: 10),
            Text(
              'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
              style: TextStyle(fontSize: 16),
            ),
            SizedBox(height: 20),
            _buildSectionTitle('Interpretation and Definitions'),
            _buildSectionTitle('Interpretation'),
            _buildSectionContent(
                'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.'),
            _buildSectionTitle('Definitions'),
            _buildSectionContent(
                'For the purposes of this Privacy Policy:\n\n'
                '• Account means a unique account created for You to access our Service or parts of our Service.\n\n'
                '• Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.\n\n'
                '• Application refers to Studyolytic, the software program provided by the Company.\n\n'
                '• Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Studyolytic.\n\n'
                '• Country refers to: Kerala, India\n\n'
                '• Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.\n\n'
                '• Personal Data is any information that relates to an identified or identifiable individual.\n\n'
                '• Service refers to the Application.\n\n'
                '• Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.\n\n'
                '• Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n\n'
                '• You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'
            ),
            SizedBox(height: 20),
            _buildSectionTitle('Collecting and Using Your Personal Data'),
            _buildSectionTitle('Types of Data Collected'),
            _buildSectionTitle('Personal Data'),
            _buildSectionContent(
                'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n\n'
                '• First name and last name\n\n'
                '• Usage Data'),
            SizedBox(height: 10),
            _buildSectionTitle('Usage Data'),
            _buildSectionContent(
                'Usage Data is collected automatically when using the Service.\n\n'
                'Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\n'
                'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.\n\n'
                'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.'),
            SizedBox(height: 20),
            // Add other sections here following the same pattern
            _buildSectionTitle('Contact Us'),
            _buildSectionContent(
              'If you have any questions about this Privacy Policy, You can contact us:\n\n'
              '• By email: kevinemmanu@gmail.com',
            ),
            SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Text(
        title,
        style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
      ),
    );
  }

  Widget _buildSectionContent(String content) {
    return Text(
      content,
      style: TextStyle(fontSize: 16),
    );
  }
}